/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Any biological, chemical, or biochemical thing. For example: a protein; a gene; a chemical; a synthetic chemical.
 */
export type BioChemEntity = BioChemEntity1 & BioChemEntity2;
export type BioChemEntity1 = Thing;
export type ImageObjectStreamId = string;
export type CreativeWorkStreamId = string;
export type ActionStreamId = string;
export type EventStreamId = string;
export type MedicalConditionStreamId = string;
export type PropertyValueStreamId = string;
export type BioChemEntityStreamId = string;
export type DefinedTermStreamId = string;
export type GeneStreamId = string;
export type TaxonStreamId = string;

/**
 * The most generic type of item.
 */
export interface Thing {
  "@context"?: string;
  "@type"?: string;
  /**
   * An additional type for the item, typically used for adding more specific types from external vocabularies in microdata syntax. This is a relationship between something and a class that the thing is in. In RDFa syntax, it is better to use the native RDFa syntax - the 'typeof' attribute - for multiple types. Schema.org tools may have only weaker understanding of extra types, in particular those defined externally.
   */
  additionalType?: string | string[];
  /**
   * An alias for the item.
   */
  alternateName?: string | string[];
  /**
   * A description of the item.
   */
  description?: string | string[];
  /**
   * A sub property of description. A short description of the item used to disambiguate from other, similar items. Information from other properties (in particular, name) may be necessary for the description to be useful for disambiguation.
   */
  disambiguatingDescription?: string | string[];
  /**
   * The identifier property represents any kind of identifier for any kind of [[Thing]], such as ISBNs, GTIN codes, UUIDs etc. Schema.org provides dedicated properties for representing many of these, either as textual strings or as URL (URI) links. See [background notes](/docs/datamodel.html#identifierBg) for more details.
   *
   */
  identifier?: string;
  /**
   * An image of the item. This can be a [[URL]] or a fully described [[ImageObject]].
   */
  image?: string | (string | ImageObjectStreamId)[];
  /**
   * Indicates a page (or other CreativeWork) for which this thing is the main entity being described. See [background notes](/docs/datamodel.html#mainEntityBackground) for details.
   */
  mainEntityOfPage?: string | (string | CreativeWorkStreamId)[];
  /**
   * The name of the item.
   */
  name?: string;
  /**
   * Indicates a potential Action, which describes an idealized action in which this thing would play an 'object' role.
   */
  potentialAction?: ActionStreamId | ActionStreamId[];
  /**
   * URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Wikidata entry, or official website.
   */
  sameAs?: string | string[];
  /**
   * A CreativeWork or Event about this Thing.
   */
  subjectOf?: (CreativeWorkStreamId | EventStreamId) | (CreativeWorkStreamId | EventStreamId)[];
  /**
   * URL of the item.
   */
  url?: string;
  [k: string]: unknown;
}
export interface BioChemEntity2 {
  /**
   * Disease associated to this BioChemEntity. Such disease can be a MedicalCondition or a URL. If you want to add an evidence supporting the association, please use PropertyValue.
   */
  associatedDisease?:
    | (string | MedicalConditionStreamId | PropertyValueStreamId)
    | (string | MedicalConditionStreamId | PropertyValueStreamId)[];
  /**
   * A BioChemEntity that is known to interact with this item.
   */
  bioChemInteraction?: BioChemEntityStreamId | BioChemEntityStreamId[];
  /**
   * A similar BioChemEntity, e.g., obtained by fingerprint similarity algorithms.
   */
  bioChemSimilarity?: BioChemEntityStreamId | BioChemEntityStreamId[];
  /**
   * A role played by the BioChemEntity within a biological context.
   */
  biologicalRole?: DefinedTermStreamId | DefinedTermStreamId[];
  /**
   * Indicates a BioChemEntity that (in some sense) has this BioChemEntity as a part.
   */
  hasBioChemEntityPart?: BioChemEntityStreamId | BioChemEntityStreamId[];
  /**
   * Molecular function performed by this BioChemEntity; please use PropertyValue if you want to include any evidence.
   */
  hasMolecularFunction?:
    | (string | DefinedTermStreamId | PropertyValueStreamId)
    | (string | DefinedTermStreamId | PropertyValueStreamId)[];
  /**
   * A common representation such as a protein sequence or chemical structure for this entity. For images use schema.org/image.
   */
  hasRepresentation?: string | (string | string | PropertyValueStreamId)[];
  /**
   * Another BioChemEntity encoding by this one.
   */
  isEncodedByBioChemEntity?: GeneStreamId | GeneStreamId[];
  /**
   * Biological process this BioChemEntity is involved in; please use PropertyValue if you want to include any evidence.
   */
  isInvolvedInBiologicalProcess?:
    | (string | DefinedTermStreamId | PropertyValueStreamId)
    | (string | DefinedTermStreamId | PropertyValueStreamId)[];
  /**
   * Subcellular location where this BioChemEntity is located; please use PropertyValue if you want to include any evidence.
   */
  isLocatedInSubcellularLocation?:
    | (string | DefinedTermStreamId | PropertyValueStreamId)
    | (string | DefinedTermStreamId | PropertyValueStreamId)[];
  /**
   * Indicates a BioChemEntity that is (in some sense) a part of this BioChemEntity.
   */
  isPartOfBioChemEntity?: BioChemEntityStreamId | BioChemEntityStreamId[];
  /**
   * The taxonomic grouping of the organism that expresses, encodes, or in someway related to the BioChemEntity.
   */
  taxonomicRange?: string | DefinedTermStreamId | TaxonStreamId;
  [k: string]: unknown;
}
