/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A type of boarding policy used by an airline.
 */
export type BoardingPolicyType = BoardingPolicyType1 & BoardingPolicyType2;
export type BoardingPolicyType1 = "GroupBoardingPolicy" | "ZoneBoardingPolicy";
export type BoardingPolicyType2 = string;
