/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The publication format of the book.
 */
export type BookFormatType = BookFormatType1 & BookFormatType2;
export type BookFormatType1 = "AudiobookFormat" | "EBook" | "GraphicNovel" | "Hardcover" | "Paperback";
export type BookFormatType2 = string;
