/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A value indicating a special usage of a car, e.g. commercial rental, driving school, or as a taxi.
 */
export type CarUsageType = CarUsageType1 & CarUsageType2;
export type CarUsageType1 = "DrivingSchoolVehicleUsage" | "RentalVehicleUsage" | "TaxiVehicleUsage";
export type CarUsageType2 = string;
