/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Enumerated options related to a ContactPoint.
 */
export type ContactPointOption = ContactPointOption1 & ContactPointOption2;
export type ContactPointOption1 = "HearingImpairedSupported" | "TollFree";
export type ContactPointOption2 = string;
