/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Indicates whether this drug is available by prescription or over-the-counter.
 */
export type DrugPrescriptionStatus = MedicalEnumeration;

/**
 * Enumerations related to health and the practice of medicine: A concept that is used to attribute a quality to another concept, as a qualifier, a collection of items or a listing of all of the elements of a set in medicine practice.
 */
export interface MedicalEnumeration {
  [k: string]: unknown;
}
