/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * EventStatusType is an enumeration type whose instances represent several states that an Event may be in.
 */
export type EventStatusType = StatusEnumeration;

/**
 * Lists or enumerations dealing with status types.
 */
export interface StatusEnumeration {
  [k: string]: unknown;
}
