/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An enumeration of genders.
 */
export type GenderType = GenderType1 & GenderType2;
export type GenderType1 = "Female" | "Male";
export type GenderType2 = string;
