/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * HealthAspectEnumeration enumerates several aspects of health content online, each of which might be described using [[hasHealthAspect]] and [[HealthTopicContent]].
 */
export type HealthAspectEnumeration = HealthAspectEnumeration1 & HealthAspectEnumeration2;
export type HealthAspectEnumeration1 =
  | "AllergiesHealthAspect"
  | "BenefitsHealthAspect"
  | "CausesHealthAspect"
  | "ContagiousnessHealthAspect"
  | "EffectivenessHealthAspect"
  | "GettingAccessHealthAspect"
  | "HowItWorksHealthAspect"
  | "HowOrWhereHealthAspect"
  | "IngredientsHealthAspect"
  | "LivingWithHealthAspect"
  | "MayTreatHealthAspect"
  | "MisconceptionsHealthAspect"
  | "OverviewHealthAspect"
  | "PatientExperienceHealthAspect"
  | "PregnancyHealthAspect"
  | "PreventionHealthAspect"
  | "PrognosisHealthAspect"
  | "RelatedTopicsHealthAspect"
  | "RisksOrComplicationsHealthAspect"
  | "SafetyHealthAspect"
  | "ScreeningHealthAspect"
  | "SeeDoctorHealthAspect"
  | "SelfCareHealthAspect"
  | "SideEffectsHealthAspect"
  | "StagesHealthAspect"
  | "SymptomsHealthAspect"
  | "TreatmentsHealthAspect"
  | "TypesHealthAspect"
  | "UsageOrScheduleHealthAspect";
export type HealthAspectEnumeration2 = string;
