/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Enumerated for values for itemListOrder for indicating how an ordered ItemList is organized.
 */
export type ItemListOrderType = ItemListOrderType1 & ItemListOrderType2;
export type ItemListOrderType1 = "ItemListOrderAscending" | "ItemListOrderDescending" | "ItemListUnordered";
export type ItemListOrderType2 = string;
