/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A listing that describes a job opening in a certain organization.
 */
export type JobPosting = JobPosting1 & JobPosting2;
export type JobPosting1 = Intangible;
/**
 * A utility class that serves as the umbrella for a number of 'intangible' things such as quantities, structured values, etc.
 */
export type Intangible = Thing;
export type ImageObjectStreamId = string;
export type CreativeWorkStreamId = string;
export type ActionStreamId = string;
export type EventStreamId = string;
export type ContactPointStreamId = string;
export type MonetaryAmountStreamId = string;
export type PriceSpecificationStreamId = string;
export type OrganizationStreamId = string;
export type MonetaryAmountDistributionStreamId = string;
export type PlaceStreamId = string;
export type CategoryCodeStreamId = string;
export type DefinedTermStreamId = string;
export type EducationalOccupationalCredentialStreamId = string;

/**
 * The most generic type of item.
 */
export interface Thing {
  "@context"?: string;
  "@type"?: string;
  /**
   * An additional type for the item, typically used for adding more specific types from external vocabularies in microdata syntax. This is a relationship between something and a class that the thing is in. In RDFa syntax, it is better to use the native RDFa syntax - the 'typeof' attribute - for multiple types. Schema.org tools may have only weaker understanding of extra types, in particular those defined externally.
   */
  additionalType?: string | string[];
  /**
   * An alias for the item.
   */
  alternateName?: string | string[];
  /**
   * A description of the item.
   */
  description?: string | string[];
  /**
   * A sub property of description. A short description of the item used to disambiguate from other, similar items. Information from other properties (in particular, name) may be necessary for the description to be useful for disambiguation.
   */
  disambiguatingDescription?: string | string[];
  /**
   * The identifier property represents any kind of identifier for any kind of [[Thing]], such as ISBNs, GTIN codes, UUIDs etc. Schema.org provides dedicated properties for representing many of these, either as textual strings or as URL (URI) links. See [background notes](/docs/datamodel.html#identifierBg) for more details.
   *
   */
  identifier?: string;
  /**
   * An image of the item. This can be a [[URL]] or a fully described [[ImageObject]].
   */
  image?: string | (string | ImageObjectStreamId)[];
  /**
   * Indicates a page (or other CreativeWork) for which this thing is the main entity being described. See [background notes](/docs/datamodel.html#mainEntityBackground) for details.
   */
  mainEntityOfPage?: string | (string | CreativeWorkStreamId)[];
  /**
   * The name of the item.
   */
  name?: string;
  /**
   * Indicates a potential Action, which describes an idealized action in which this thing would play an 'object' role.
   */
  potentialAction?: ActionStreamId | ActionStreamId[];
  /**
   * URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Wikidata entry, or official website.
   */
  sameAs?: string | string[];
  /**
   * A CreativeWork or Event about this Thing.
   */
  subjectOf?: (CreativeWorkStreamId | EventStreamId) | (CreativeWorkStreamId | EventStreamId)[];
  /**
   * URL of the item.
   */
  url?: string;
  [k: string]: unknown;
}
export interface JobPosting2 {
  /**
   * The location(s) applicants can apply from. This is usually used for telecommuting jobs where the applicant does not need to be in a physical office. Note: This should not be used for citizenship or work visa requirements.
   */
  applicantLocationRequirements?: string;
  /**
   * Contact details for further information relevant to this job posting.
   */
  applicationContact?: ContactPointStreamId | ContactPointStreamId[];
  /**
   * The base salary of the job or of an employee in an EmployeeRole.
   */
  baseSalary?: number | MonetaryAmountStreamId | PriceSpecificationStreamId;
  /**
   * Description of benefits associated with the job.
   */
  benefits?: string;
  /**
   * Publication date of an online listing.
   */
  datePosted?: string;
  /**
   * Indicates whether an [[url]] that is associated with a [[JobPosting]] enables direct application for the job, via the posting website. A job posting is considered to have directApply of [[True]] if an application process for the specified job can be directly initiated via the url(s) given (noting that e.g. multiple internet domains might nevertheless be involved at an implementation level). A value of [[False]] is appropriate if there is no clear path to applying directly online for the specified job, navigating directly from the JobPosting url(s) supplied.
   */
  directApply?: boolean;
  /**
   * Educational background needed for the position or Occupation.
   */
  educationRequirements?: string;
  /**
   * The legal requirements such as citizenship, visa and other documentation required for an applicant to this job.
   */
  eligibilityToWorkRequirement?: string;
  /**
   * A description of the employer, career opportunities and work environment for this position.
   */
  employerOverview?: string | string[];
  /**
   * Type of employment (e.g. full-time, part-time, contract, temporary, seasonal, internship).
   */
  employmentType?: string | string[];
  /**
   * Indicates the department, unit and/or facility where the employee reports and/or in which the job is to be performed.
   */
  employmentUnit?: OrganizationStreamId | OrganizationStreamId[];
  /**
   * An estimated salary for a job posting or occupation, based on a variety of variables including, but not limited to industry, job title, and location. Estimated salaries  are often computed by outside organizations rather than the hiring organization, who may not have committed to the estimated value.
   */
  estimatedSalary?:
    | (number | MonetaryAmountStreamId | MonetaryAmountDistributionStreamId)
    | (number | MonetaryAmountStreamId | MonetaryAmountDistributionStreamId)[];
  /**
   * Indicates whether a [[JobPosting]] will accept experience (as indicated by [[OccupationalExperienceRequirements]]) in place of its formal educational qualifications (as indicated by [[educationRequirements]]). If true, indicates that satisfying one of these requirements is sufficient.
   */
  experienceInPlaceOfEducation?: boolean;
  /**
   * Description of skills and experience needed for the position or Occupation.
   */
  experienceRequirements?: string;
  /**
   * Organization offering the job position.
   */
  hiringOrganization?: string;
  /**
   * Description of bonus and commission compensation aspects of the job.
   */
  incentiveCompensation?: string | string[];
  /**
   * Description of bonus and commission compensation aspects of the job.
   */
  incentives?: string | string[];
  /**
   * The industry associated with the job position.
   */
  industry?: string;
  /**
   * Description of benefits associated with the job.
   */
  jobBenefits?: string | string[];
  /**
   * An indicator as to whether a position is available for an immediate start.
   */
  jobImmediateStart?: boolean;
  /**
   * A (typically single) geographic location associated with the job position.
   */
  jobLocation?: PlaceStreamId | PlaceStreamId[];
  /**
   * A description of the job location (e.g TELECOMMUTE for telecommute jobs).
   */
  jobLocationType?: string | string[];
  /**
   * The date on which a successful applicant for this job would be expected to start work. Choose a specific date in the future or use the jobImmediateStart property to indicate the position is to be filled as soon as possible.
   */
  jobStartDate?: string;
  /**
   * A category describing the job, preferably using a term from a taxonomy such as [BLS O*NET-SOC](http://www.onetcenter.org/taxonomy.html), [ISCO-08](https://www.ilo.org/public/english/bureau/stat/isco/isco08/) or similar, with the property repeated for each applicable value. Ideally the taxonomy should be identified, and both the textual label and formal code for the category should be provided.\n
   * Note: for historical reasons, any textual label and formal code provided as a literal may be assumed to be from O*NET-SOC.
   */
  occupationalCategory?: string | (string | CategoryCodeStreamId)[];
  /**
   * A description of the types of physical activity associated with the job. Defined terms such as those in O*net may be used, but note that there is no way to specify the level of ability as well as its nature when using a defined term.
   */
  physicalRequirement?: string | (string | string | DefinedTermStreamId)[];
  /**
   * Specific qualifications required for this role or Occupation.
   */
  qualifications?: string | (string | EducationalOccupationalCredentialStreamId)[];
  /**
   * The Occupation for the JobPosting.
   */
  relevantOccupation?: string;
  /**
   * Responsibilities associated with this role or Occupation.
   */
  responsibilities?: string | string[];
  /**
   * The currency (coded using [ISO 4217](http://en.wikipedia.org/wiki/ISO_4217) ) used for the main salary information in this job posting or for this employee.
   */
  salaryCurrency?: string;
  /**
   * A description of any security clearance requirements of the job.
   */
  securityClearanceRequirement?: string | (string | string)[];
  /**
   * A description of any sensory requirements and levels necessary to function on the job, including hearing and vision. Defined terms such as those in O*net may be used, but note that there is no way to specify the level of ability as well as its nature when using a defined term.
   */
  sensoryRequirement?: string | (string | string | DefinedTermStreamId)[];
  /**
   * A statement of knowledge, skill, ability, task or any other assertion expressing a competency that is desired or required to fulfill this role or to work in this occupation.
   */
  skills?: string | (string | DefinedTermStreamId)[];
  /**
   * Any special commitments associated with this job posting. Valid entries include VeteranCommit, MilitarySpouseCommit, etc.
   */
  specialCommitments?: string | string[];
  /**
   * The title of the job.
   */
  title?: string;
  /**
   * The number of positions open for this job posting. Use a positive integer. Do not use if the number of positions is unclear or not known.
   */
  totalJobOpenings?: number;
  /**
   * The date after when the item is not valid. For example the end of an offer, salary period, or a period of opening hours.
   */
  validThrough?: string;
  /**
   * The typical working hours for this job (e.g. 1st shift, night shift, 8am-5pm).
   */
  workHours?: string;
  [k: string]: unknown;
}
