/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A list of possible statuses for the legal force of a legislation.
 */
export type LegalForceStatus = StatusEnumeration;

/**
 * Lists or enumerations dealing with status types.
 */
export interface StatusEnumeration {
  [k: string]: unknown;
}
