/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An enumeration of several kinds of Map.
 */
export type MapCategoryType = MapCategoryType1 & MapCategoryType2;
export type MapCategoryType1 = "ParkingMap" | "SeatingMap" | "TransitMap" | "VenueMap";
export type MapCategoryType2 = string;
