/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Any condition of the human body that affects the normal functioning of a person, whether physically or mentally. Includes diseases, injuries, disabilities, disorders, syndromes, etc.
 */
export type MedicalCondition = MedicalCondition1 & MedicalCondition2;
export type MedicalCondition1 = MedicalEntity;
/**
 * The most generic type of entity related to health and the practice of medicine.
 */
export type MedicalEntity = Thing;
export type ImageObjectStreamId = string;
export type CreativeWorkStreamId = string;
export type ActionStreamId = string;
export type EventStreamId = string;
export type AnatomicalStructureStreamId = string;
export type AnatomicalSystemStreamId = string;
export type SuperficialAnatomyStreamId = string;
export type DDxElementStreamId = string;
export type DrugStreamId = string;
export type MedicalTherapyStreamId = string;
export type MedicalRiskFactorStreamId = string;
export type MedicalSignOrSymptomStreamId = string;
export type EventStatusTypeStreamId = string;
export type MedicalStudyStatusStreamId = string;
export type MedicalTestStreamId = string;

/**
 * The most generic type of item.
 */
export interface Thing {
  "@context"?: string;
  "@type"?: string;
  /**
   * An additional type for the item, typically used for adding more specific types from external vocabularies in microdata syntax. This is a relationship between something and a class that the thing is in. In RDFa syntax, it is better to use the native RDFa syntax - the 'typeof' attribute - for multiple types. Schema.org tools may have only weaker understanding of extra types, in particular those defined externally.
   */
  additionalType?: string | string[];
  /**
   * An alias for the item.
   */
  alternateName?: string | string[];
  /**
   * A description of the item.
   */
  description?: string | string[];
  /**
   * A sub property of description. A short description of the item used to disambiguate from other, similar items. Information from other properties (in particular, name) may be necessary for the description to be useful for disambiguation.
   */
  disambiguatingDescription?: string | string[];
  /**
   * The identifier property represents any kind of identifier for any kind of [[Thing]], such as ISBNs, GTIN codes, UUIDs etc. Schema.org provides dedicated properties for representing many of these, either as textual strings or as URL (URI) links. See [background notes](/docs/datamodel.html#identifierBg) for more details.
   *
   */
  identifier?: string;
  /**
   * An image of the item. This can be a [[URL]] or a fully described [[ImageObject]].
   */
  image?: string | (string | ImageObjectStreamId)[];
  /**
   * Indicates a page (or other CreativeWork) for which this thing is the main entity being described. See [background notes](/docs/datamodel.html#mainEntityBackground) for details.
   */
  mainEntityOfPage?: string | (string | CreativeWorkStreamId)[];
  /**
   * The name of the item.
   */
  name?: string;
  /**
   * Indicates a potential Action, which describes an idealized action in which this thing would play an 'object' role.
   */
  potentialAction?: ActionStreamId | ActionStreamId[];
  /**
   * URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Wikidata entry, or official website.
   */
  sameAs?: string | string[];
  /**
   * A CreativeWork or Event about this Thing.
   */
  subjectOf?: (CreativeWorkStreamId | EventStreamId) | (CreativeWorkStreamId | EventStreamId)[];
  /**
   * URL of the item.
   */
  url?: string;
  [k: string]: unknown;
}
export interface MedicalCondition2 {
  /**
   * The anatomy of the underlying organ system or structures associated with this entity.
   */
  associatedAnatomy?: AnatomicalStructureStreamId | AnatomicalSystemStreamId | SuperficialAnatomyStreamId;
  /**
   * One of a set of differential diagnoses for the condition. Specifically, a closely-related or competing diagnosis typically considered later in the cognitive process whereby this medical condition is distinguished from others most likely responsible for a similar collection of signs and symptoms to reach the most parsimonious diagnosis or diagnoses in a patient.
   */
  differentialDiagnosis?: DDxElementStreamId | DDxElementStreamId[];
  /**
   * Specifying a drug or medicine used in a medication procedure.
   */
  drug?: DrugStreamId | DrugStreamId[];
  /**
   * The characteristics of associated patients, such as age, gender, race etc.
   */
  epidemiology?: string;
  /**
   * The likely outcome in either the short term or long term of the medical condition.
   */
  expectedPrognosis?: string;
  /**
   * The expected progression of the condition if it is not treated and allowed to progress naturally.
   */
  naturalProgression?: string;
  /**
   * Changes in the normal mechanical, physical, and biochemical functions that are associated with this activity or condition.
   */
  pathophysiology?: string | string[];
  /**
   * A possible unexpected and unfavorable evolution of a medical condition. Complications may include worsening of the signs or symptoms of the disease, extension of the condition to other organ systems, etc.
   */
  possibleComplication?: string | string[];
  /**
   * A possible treatment to address this condition, sign or symptom.
   */
  possibleTreatment?: MedicalTherapyStreamId | MedicalTherapyStreamId[];
  /**
   * A preventative therapy used to prevent an initial occurrence of the medical condition, such as vaccination.
   */
  primaryPrevention?: MedicalTherapyStreamId | MedicalTherapyStreamId[];
  /**
   * A modifiable or non-modifiable factor that increases the risk of a patient contracting this condition, e.g. age,  coexisting condition.
   */
  riskFactor?: MedicalRiskFactorStreamId | MedicalRiskFactorStreamId[];
  /**
   * A preventative therapy used to prevent reoccurrence of the medical condition after an initial episode of the condition.
   */
  secondaryPrevention?: MedicalTherapyStreamId | MedicalTherapyStreamId[];
  /**
   * A sign or symptom of this condition. Signs are objective or physically observable manifestations of the medical condition while symptoms are the subjective experience of the medical condition.
   */
  signOrSymptom?: MedicalSignOrSymptomStreamId | MedicalSignOrSymptomStreamId[];
  /**
   * The stage of the condition, if applicable.
   */
  stage?: string;
  /**
   * The status of the study (enumerated).
   */
  status?: string | EventStatusTypeStreamId | MedicalStudyStatusStreamId;
  /**
   * A medical test typically performed given this condition.
   */
  typicalTest?: MedicalTestStreamId | MedicalTestStreamId[];
  [k: string]: unknown;
}
