/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A MerchantReturnPolicy provides information about product return policies associated with an [[Organization]], [[Product]], or [[Offer]].
 */
export type MerchantReturnPolicy = MerchantReturnPolicy1 & MerchantReturnPolicy2;
export type MerchantReturnPolicy1 = Intangible;
/**
 * A utility class that serves as the umbrella for a number of 'intangible' things such as quantities, structured values, etc.
 */
export type Intangible = Thing;
export type ImageObjectStreamId = string;
export type CreativeWorkStreamId = string;
export type ActionStreamId = string;
export type EventStreamId = string;
export type PropertyValueStreamId = string;
export type OfferItemConditionStreamId = string;
export type MonetaryAmountStreamId = string;
export type RefundTypeEnumerationStreamId = string;
export type MerchantReturnEnumerationStreamId = string;
export type MerchantReturnPolicySeasonalOverrideStreamId = string;

/**
 * The most generic type of item.
 */
export interface Thing {
  "@context"?: string;
  "@type"?: string;
  /**
   * An additional type for the item, typically used for adding more specific types from external vocabularies in microdata syntax. This is a relationship between something and a class that the thing is in. In RDFa syntax, it is better to use the native RDFa syntax - the 'typeof' attribute - for multiple types. Schema.org tools may have only weaker understanding of extra types, in particular those defined externally.
   */
  additionalType?: string | string[];
  /**
   * An alias for the item.
   */
  alternateName?: string | string[];
  /**
   * A description of the item.
   */
  description?: string | string[];
  /**
   * A sub property of description. A short description of the item used to disambiguate from other, similar items. Information from other properties (in particular, name) may be necessary for the description to be useful for disambiguation.
   */
  disambiguatingDescription?: string | string[];
  /**
   * The identifier property represents any kind of identifier for any kind of [[Thing]], such as ISBNs, GTIN codes, UUIDs etc. Schema.org provides dedicated properties for representing many of these, either as textual strings or as URL (URI) links. See [background notes](/docs/datamodel.html#identifierBg) for more details.
   *
   */
  identifier?: string;
  /**
   * An image of the item. This can be a [[URL]] or a fully described [[ImageObject]].
   */
  image?: string | (string | ImageObjectStreamId)[];
  /**
   * Indicates a page (or other CreativeWork) for which this thing is the main entity being described. See [background notes](/docs/datamodel.html#mainEntityBackground) for details.
   */
  mainEntityOfPage?: string | (string | CreativeWorkStreamId)[];
  /**
   * The name of the item.
   */
  name?: string;
  /**
   * Indicates a potential Action, which describes an idealized action in which this thing would play an 'object' role.
   */
  potentialAction?: ActionStreamId | ActionStreamId[];
  /**
   * URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Wikidata entry, or official website.
   */
  sameAs?: string | string[];
  /**
   * A CreativeWork or Event about this Thing.
   */
  subjectOf?: (CreativeWorkStreamId | EventStreamId) | (CreativeWorkStreamId | EventStreamId)[];
  /**
   * URL of the item.
   */
  url?: string;
  [k: string]: unknown;
}
export interface MerchantReturnPolicy2 {
  /**
   * A property-value pair representing an additional characteristics of the entitity, e.g. a product feature or another characteristic for which there is no matching property in schema.org.\n\nNote: Publishers should be aware that applications designed to use specific schema.org properties (e.g. https://schema.org/width, https://schema.org/color, https://schema.org/gtin13, ...) will typically expect such data to be provided using those properties, rather than using the generic property/value mechanism.
   *
   */
  additionalProperty?: PropertyValueStreamId | PropertyValueStreamId[];
  /**
   * The type of return fees if the product is returned due to customer remorse.
   */
  customerRemorseReturnFees?: string;
  /**
   * The method (from an enumeration) by which the customer obtains a return shipping label for a product returned due to customer remorse.
   */
  customerRemorseReturnLabelSource?: string;
  /**
   * The amount of shipping costs if a product is returned due to customer remorse. Applicable when property [[customerRemorseReturnFees]] equals [[ReturnShippingFees]].
   */
  customerRemorseReturnShippingFeesAmount?: string;
  /**
   * Are in-store returns offered? (for more advanced return methods use the [[returnMethod]] property)
   */
  inStoreReturnsOffered?: boolean;
  /**
   * A predefined value from OfferItemCondition specifying the condition of the product or service, or the products or services included in the offer. Also used for product return policies to specify the condition of products accepted for returns.
   */
  itemCondition?: OfferItemConditionStreamId | OfferItemConditionStreamId[];
  /**
   * The type of return fees for returns of defect products.
   */
  itemDefectReturnFees?: string;
  /**
   * The method (from an enumeration) by which the customer obtains a return shipping label for a defect product.
   */
  itemDefectReturnLabelSource?: string;
  /**
   * Amount of shipping costs for defect product returns. Applicable when property [[itemDefectReturnFees]] equals [[ReturnShippingFees]].
   */
  itemDefectReturnShippingFeesAmount?: MonetaryAmountStreamId | MonetaryAmountStreamId[];
  /**
   * Specifies either a fixed return date or the number of days (from the delivery date) that a product can be returned. Used when the [[returnPolicyCategory]] property is specified as [[MerchantReturnFiniteReturnWindow]].
   */
  merchantReturnDays?: (number | string) | (number | string | string)[];
  /**
   * Specifies a Web page or service by URL, for product returns.
   */
  merchantReturnLink?: string | string[];
  /**
   * A refund type, from an enumerated list.
   */
  refundType?: RefundTypeEnumerationStreamId | RefundTypeEnumerationStreamId[];
  /**
   * Use [[MonetaryAmount]] to specify a fixed restocking fee for product returns, or use [[Number]] to specify a percentage of the product price paid by the customer.
   */
  restockingFee?: (number | MonetaryAmountStreamId) | (number | MonetaryAmountStreamId)[];
  /**
   * The type of return fees for purchased products (for any return reason)
   */
  returnFees?: string;
  /**
   * The method (from an enumeration) by which the customer obtains a return shipping label for a product returned for any reason.
   */
  returnLabelSource?: string;
  /**
   * The type of return method offered, specified from an enumeration.
   */
  returnMethod?: string;
  /**
   * Specifies an applicable return policy (from an enumeration).
   */
  returnPolicyCategory?: MerchantReturnEnumerationStreamId | MerchantReturnEnumerationStreamId[];
  /**
   * The country where the product has to be sent to for returns, for example "Ireland" using the [[name]] property of [[Country]]. You can also provide the two-letter [ISO 3166-1 alpha-2 country code](http://en.wikipedia.org/wiki/ISO_3166-1). Note that this can be different from the country where the product was originally shipped from or sent too.
   */
  returnPolicyCountry?: string;
  /**
   * Seasonal override of a return policy.
   */
  returnPolicySeasonalOverride?:
    | MerchantReturnPolicySeasonalOverrideStreamId
    | MerchantReturnPolicySeasonalOverrideStreamId[];
  /**
   * Amount of shipping costs for product returns (for any reason). Applicable when property [[returnFees]] equals [[ReturnShippingFees]].
   */
  returnShippingFeesAmount?: MonetaryAmountStreamId | MonetaryAmountStreamId[];
  [k: string]: unknown;
}
