/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Format of this release (the type of recording media used, ie. compact disc, digital media, LP, etc.).
 */
export type MusicReleaseFormatType = MusicReleaseFormatType1 & MusicReleaseFormatType2;
export type MusicReleaseFormatType1 =
  | "CDFormat"
  | "CassetteFormat"
  | "DVDFormat"
  | "DigitalAudioTapeFormat"
  | "DigitalFormat"
  | "LaserDiscFormat"
  | "VinylFormat";
export type MusicReleaseFormatType2 = string;
