/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The kind of release which this album is: single, EP or album.
 */
export type MusicAlbumReleaseType = MusicAlbumReleaseType1 & MusicAlbumReleaseType2;
export type MusicAlbumReleaseType1 = "AlbumRelease" | "BroadcastRelease" | "EPRelease" | "SingleRelease";
export type MusicAlbumReleaseType2 = string;
