/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A list of possible conditions for the item.
 */
export type OfferItemCondition = OfferItemCondition1 & OfferItemCondition2;
export type OfferItemCondition1 = "DamagedCondition" | "NewCondition" | "RefurbishedCondition" | "UsedCondition";
export type OfferItemCondition2 = string;
