/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An organization such as a school, NGO, corporation, club, etc.
 */
export type Organization = Organization1 & Organization2;
export type Organization1 = Thing;
export type ImageObjectStreamId = string;
export type CreativeWorkStreamId = string;
export type ActionStreamId = string;
export type EventStreamId = string;
export type PersonStreamId = string;
export type AdministrativeAreaStreamId = string;
export type GeoShapeStreamId = string;
export type PlaceStreamId = string;
export type BrandStreamId = string;
export type OrganizationStreamId = string;
export type ContactPointStreamId = string;
export type ArticleStreamId = string;
export type EducationalOccupationalCredentialStreamId = string;
export type MerchantReturnPolicyStreamId = string;
export type OfferCatalogStreamId = string;
export type ThingStreamId = string;
export type LanguageStreamId = string;
export type PostalAddressStreamId = string;
export type VirtualLocationStreamId = string;
export type OfferStreamId = string;
export type ProgramMembershipStreamId = string;
export type NonprofitTypeStreamId = string;
export type AboutPageStreamId = string;
export type OwnershipInfoStreamId = string;
export type ProductStreamId = string;
export type ReviewStreamId = string;
export type DemandStreamId = string;

/**
 * The most generic type of item.
 */
export interface Thing {
  "@context"?: string;
  "@type"?: string;
  /**
   * An additional type for the item, typically used for adding more specific types from external vocabularies in microdata syntax. This is a relationship between something and a class that the thing is in. In RDFa syntax, it is better to use the native RDFa syntax - the 'typeof' attribute - for multiple types. Schema.org tools may have only weaker understanding of extra types, in particular those defined externally.
   */
  additionalType?: string | string[];
  /**
   * An alias for the item.
   */
  alternateName?: string | string[];
  /**
   * A description of the item.
   */
  description?: string | string[];
  /**
   * A sub property of description. A short description of the item used to disambiguate from other, similar items. Information from other properties (in particular, name) may be necessary for the description to be useful for disambiguation.
   */
  disambiguatingDescription?: string | string[];
  /**
   * The identifier property represents any kind of identifier for any kind of [[Thing]], such as ISBNs, GTIN codes, UUIDs etc. Schema.org provides dedicated properties for representing many of these, either as textual strings or as URL (URI) links. See [background notes](/docs/datamodel.html#identifierBg) for more details.
   *
   */
  identifier?: string;
  /**
   * An image of the item. This can be a [[URL]] or a fully described [[ImageObject]].
   */
  image?: string | (string | ImageObjectStreamId)[];
  /**
   * Indicates a page (or other CreativeWork) for which this thing is the main entity being described. See [background notes](/docs/datamodel.html#mainEntityBackground) for details.
   */
  mainEntityOfPage?: string | (string | CreativeWorkStreamId)[];
  /**
   * The name of the item.
   */
  name?: string;
  /**
   * Indicates a potential Action, which describes an idealized action in which this thing would play an 'object' role.
   */
  potentialAction?: ActionStreamId | ActionStreamId[];
  /**
   * URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Wikidata entry, or official website.
   */
  sameAs?: string | string[];
  /**
   * A CreativeWork or Event about this Thing.
   */
  subjectOf?: (CreativeWorkStreamId | EventStreamId) | (CreativeWorkStreamId | EventStreamId)[];
  /**
   * URL of the item.
   */
  url?: string;
  [k: string]: unknown;
}
export interface Organization2 {
  /**
   * For a [[NewsMediaOrganization]] or other news-related [[Organization]], a statement about public engagement activities (for news media, the newsroom’s), including involving the public - digitally or otherwise -- in coverage decisions, reporting and activities after publication.
   */
  actionableFeedbackPolicy?: string | (string | CreativeWorkStreamId)[];
  /**
   * Physical address of the item.
   */
  address?: string;
  /**
   * The overall rating, based on a collection of reviews or ratings, of the item.
   */
  aggregateRating?: string;
  /**
   * Alumni of an organization.
   */
  alumni?: PersonStreamId | PersonStreamId[];
  /**
   * The geographic area where a service or offered item is provided.
   */
  areaServed?: string | AdministrativeAreaStreamId | GeoShapeStreamId | PlaceStreamId;
  /**
   * An award won by or for this item.
   */
  award?: string | string[];
  /**
   * Awards won by or for this item.
   */
  awards?: string | string[];
  /**
   * The brand(s) associated with a product or service, or the brand(s) maintained by an organization or business person.
   */
  brand?: BrandStreamId | OrganizationStreamId;
  /**
   * A contact point for a person or organization.
   */
  contactPoint?: ContactPointStreamId | ContactPointStreamId[];
  /**
   * A contact point for a person or organization.
   */
  contactPoints?: ContactPointStreamId | ContactPointStreamId[];
  /**
   * For an [[Organization]] (e.g. [[NewsMediaOrganization]]), a statement describing (in news media, the newsroom’s) disclosure and correction policy for errors.
   */
  correctionsPolicy?: string | (string | CreativeWorkStreamId)[];
  /**
   * A relationship between an organization and a department of that organization, also described as an organization (allowing different urls, logos, opening hours). For example: a store with a pharmacy, or a bakery with a cafe.
   */
  department?: OrganizationStreamId | OrganizationStreamId[];
  /**
   * The date that this organization was dissolved.
   */
  dissolutionDate?: string;
  /**
   * Statement on diversity policy by an [[Organization]] e.g. a [[NewsMediaOrganization]]. For a [[NewsMediaOrganization]], a statement describing the newsroom’s diversity policy on both staffing and sources, typically providing staffing data.
   */
  diversityPolicy?: string | (string | CreativeWorkStreamId)[];
  /**
   * For an [[Organization]] (often but not necessarily a [[NewsMediaOrganization]]), a report on staffing diversity issues. In a news context this might be for example ASNE or RTDNA (US) reports, or self-reported.
   */
  diversityStaffingReport?: string | (string | ArticleStreamId)[];
  /**
   * The Dun & Bradstreet DUNS number for identifying an organization or business person.
   */
  duns?: string;
  /**
   * Email address.
   */
  email?: string | string[];
  /**
   * Someone working for this organization.
   */
  employee?: PersonStreamId | PersonStreamId[];
  /**
   * People working for this organization.
   */
  employees?: PersonStreamId | PersonStreamId[];
  /**
   * Statement about ethics policy, e.g. of a [[NewsMediaOrganization]] regarding journalistic and publishing practices, or of a [[Restaurant]], a page describing food source policies. In the case of a [[NewsMediaOrganization]], an ethicsPolicy is typically a statement describing the personal, organizational, and corporate standards of behavior expected by the organization.
   */
  ethicsPolicy?: string | (string | CreativeWorkStreamId)[];
  /**
   * Upcoming or past event associated with this place, organization, or action.
   */
  event?: EventStreamId | EventStreamId[];
  /**
   * Upcoming or past events associated with this place or organization.
   */
  events?: EventStreamId | EventStreamId[];
  /**
   * The fax number.
   */
  faxNumber?: string;
  /**
   * A person who founded this organization.
   */
  founder?: PersonStreamId | PersonStreamId[];
  /**
   * A person who founded this organization.
   */
  founders?: PersonStreamId | PersonStreamId[];
  /**
   * The date that this organization was founded.
   */
  foundingDate?: string;
  /**
   * The place where the Organization was founded.
   */
  foundingLocation?: string;
  /**
   * A person or organization that supports (sponsors) something through some kind of financial contribution.
   */
  funder?: (OrganizationStreamId | PersonStreamId) | (OrganizationStreamId | PersonStreamId)[];
  /**
   * The [Global Location Number](http://www.gs1.org/gln) (GLN, sometimes also referred to as International Location Number or ILN) of the respective organization, person, or place. The GLN is a 13-digit number used to identify parties and physical locations.
   */
  globalLocationNumber?: string;
  /**
   * A credential awarded to the Person or Organization.
   */
  hasCredential?: EducationalOccupationalCredentialStreamId | EducationalOccupationalCredentialStreamId[];
  /**
   * Specifies a MerchantReturnPolicy that may be applicable.
   */
  hasMerchantReturnPolicy?: MerchantReturnPolicyStreamId | MerchantReturnPolicyStreamId[];
  /**
   * Indicates an OfferCatalog listing for this Organization, Person, or Service.
   */
  hasOfferCatalog?: OfferCatalogStreamId | OfferCatalogStreamId[];
  /**
   * Points-of-Sales operated by the organization or person.
   */
  hasPOS?: PlaceStreamId | PlaceStreamId[];
  /**
   * The number of interactions for the CreativeWork using the WebSite or SoftwareApplication. The most specific child type of InteractionCounter should be used.
   */
  interactionStatistic?: string;
  /**
   * The International Standard of Industrial Classification of All Economic Activities (ISIC), Revision 4 code for a particular organization, business person, or place.
   */
  isicV4?: string;
  /**
   * Of a [[Person]], and less typically of an [[Organization]], to indicate a topic that is known about - suggesting possible expertise but not implying it. We do not distinguish skill levels here, or relate this to educational content, events, objectives or [[JobPosting]] descriptions.
   */
  knowsAbout?: string | (string | string | ThingStreamId)[];
  /**
   * Of a [[Person]], and less typically of an [[Organization]], to indicate a known language. We do not distinguish skill levels or reading/writing/speaking/signing here. Use language codes from the [IETF BCP 47 standard](http://tools.ietf.org/html/bcp47).
   */
  knowsLanguage?: string | (string | LanguageStreamId)[];
  /**
   * The official name of the organization, e.g. the registered company name.
   */
  legalName?: string;
  /**
   * An organization identifier that uniquely identifies a legal entity as defined in ISO 17442.
   */
  leiCode?: string | string[];
  /**
   * The location of, for example, where an event is happening, where an organization is located, or where an action takes place.
   */
  location?: string | PlaceStreamId | PostalAddressStreamId | VirtualLocationStreamId;
  /**
   * An associated logo.
   */
  logo?: string | (string | ImageObjectStreamId)[];
  /**
   * A pointer to products or services offered by the organization or person.
   */
  makesOffer?: OfferStreamId | OfferStreamId[];
  /**
   * A member of an Organization or a ProgramMembership. Organizations can be members of organizations; ProgramMembership is typically for individuals.
   */
  member?: (OrganizationStreamId | PersonStreamId) | (OrganizationStreamId | PersonStreamId)[];
  /**
   * An Organization (or ProgramMembership) to which this Person or Organization belongs.
   */
  memberOf?: (OrganizationStreamId | ProgramMembershipStreamId) | (OrganizationStreamId | ProgramMembershipStreamId)[];
  /**
   * A member of this organization.
   */
  members?: (OrganizationStreamId | PersonStreamId) | (OrganizationStreamId | PersonStreamId)[];
  /**
   * The North American Industry Classification System (NAICS) code for a particular organization or business person.
   */
  naics?: string;
  /**
   * nonprofit Status indicates the legal status of a non-profit organization in its primary place of business.
   */
  nonprofitStatus?: NonprofitTypeStreamId | NonprofitTypeStreamId[];
  /**
   * The number of employees in an organization e.g. business.
   */
  numberOfEmployees?: string;
  /**
   * For an [[Organization]] (often but not necessarily a [[NewsMediaOrganization]]), a description of organizational ownership structure; funding and grants. In a news/media setting, this is with particular reference to editorial independence.   Note that the [[funder]] is also available and can be used to make basic funder information machine-readable.
   */
  ownershipFundingInfo?:
    | (string | AboutPageStreamId | CreativeWorkStreamId)
    | (string | string | AboutPageStreamId | CreativeWorkStreamId)[];
  /**
   * Products owned by the organization or person.
   */
  owns?: (OwnershipInfoStreamId | ProductStreamId) | (OwnershipInfoStreamId | ProductStreamId)[];
  /**
   * The larger organization that this organization is a [[subOrganization]] of, if any.
   */
  parentOrganization?: string;
  /**
   * The publishingPrinciples property indicates (typically via [[URL]]) a document describing the editorial principles of an [[Organization]] (or individual e.g. a [[Person]] writing a blog) that relate to their activities as a publisher, e.g. ethics or diversity policies. When applied to a [[CreativeWork]] (e.g. [[NewsArticle]]) the principles are those of the party primarily responsible for the creation of the [[CreativeWork]].
   *
   * While such policies are most typically expressed in natural language, sometimes related information (e.g. indicating a [[funder]]) can be expressed using schema.org terminology.
   *
   */
  publishingPrinciples?: string;
  /**
   * A review of the item.
   */
  review?: ReviewStreamId | ReviewStreamId[];
  /**
   * Review of the item.
   */
  reviews?: ReviewStreamId | ReviewStreamId[];
  /**
   * A pointer to products or services sought by the organization or person (demand).
   */
  seeks?: DemandStreamId | DemandStreamId[];
  /**
   * The geographic area where the service is provided.
   */
  serviceArea?: AdministrativeAreaStreamId | GeoShapeStreamId | PlaceStreamId;
  /**
   * A slogan or motto associated with the item.
   */
  slogan?: string | string[];
  /**
   * A person or organization that supports a thing through a pledge, promise, or financial contribution. e.g. a sponsor of a Medical Study or a corporate sponsor of an event.
   */
  sponsor?: (OrganizationStreamId | PersonStreamId) | (OrganizationStreamId | PersonStreamId)[];
  /**
   * A relationship between two organizations where the first includes the second, e.g., as a subsidiary. See also: the more specific 'department' property.
   */
  subOrganization?: OrganizationStreamId | OrganizationStreamId[];
  /**
   * The Tax / Fiscal ID of the organization or person, e.g. the TIN in the US or the CIF/NIF in Spain.
   */
  taxID?: string;
  /**
   * The telephone number.
   */
  telephone?: string;
  /**
   * For an [[Organization]] (typically a [[NewsMediaOrganization]]), a statement about policy on use of unnamed sources and the decision process required.
   */
  unnamedSourcesPolicy?: string | (string | CreativeWorkStreamId)[];
  /**
   * The Value-added Tax ID of the organization or person.
   */
  vatID?: string;
  [k: string]: unknown;
}
