/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Categories of physical activity, organized by physiologic classification.
 */
export type PhysicalActivityCategory = PhysicalActivityCategory1 & PhysicalActivityCategory2;
export type PhysicalActivityCategory1 =
  | "AerobicActivity"
  | "AnaerobicActivity"
  | "Balance"
  | "Flexibility"
  | "LeisureTimeActivity"
  | "OccupationalActivity"
  | "StrengthTraining";
export type PhysicalActivityCategory2 = string;
