/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Enumerates different price components that together make up the total price for an offered product.
 */
export type PriceComponentTypeEnumeration = PriceComponentTypeEnumeration1 & PriceComponentTypeEnumeration2;
export type PriceComponentTypeEnumeration1 =
  | "ActivationFee"
  | "CleaningFee"
  | "DistanceFee"
  | "Downpayment"
  | "Installment"
  | "Subscription";
export type PriceComponentTypeEnumeration2 = string;
