/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Enumerates several kinds of product return refund types.
 */
export type RefundTypeEnumeration = RefundTypeEnumeration1 & RefundTypeEnumeration2;
export type RefundTypeEnumeration1 = "ExchangeRefund" | "FullRefund" | "StoreCreditRefund";
export type RefundTypeEnumeration2 = string;
