/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Enumerates several types of return labels for product returns.
 */
export type ReturnLabelSourceEnumeration = ReturnLabelSourceEnumeration1 & ReturnLabelSourceEnumeration2;
export type ReturnLabelSourceEnumeration1 =
  | "ReturnLabelCustomerResponsibility"
  | "ReturnLabelDownloadAndPrint"
  | "ReturnLabelInBox";
export type ReturnLabelSourceEnumeration2 = string;
