/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Enumerates several kinds of policies for product return fees.
 */
export type ReturnFeesEnumeration = ReturnFeesEnumeration1 & ReturnFeesEnumeration2;
export type ReturnFeesEnumeration1 =
  | "FreeReturn"
  | "OriginalShippingFees"
  | "RestockingFees"
  | "ReturnFeesCustomerResponsibility"
  | "ReturnShippingFees";
export type ReturnFeesEnumeration2 = string;
