/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * RsvpResponseType is an enumeration type whose instances represent responding to an RSVP request.
 */
export type RsvpResponseType = RsvpResponseType1 & RsvpResponseType2;
export type RsvpResponseType1 = "RsvpResponseMaybe" | "RsvpResponseNo" | "RsvpResponseYes";
export type RsvpResponseType2 = string;
