/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Any branch of a field in which people typically develop specific expertise, usually after significant study, time, and effort.
 */
export interface Specialty {
  [k: string]: unknown;
}
