/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Enumerates common size groups (also known as "size types") for wearable products.
 */
export type WearableSizeGroupEnumeration = SizeGroupEnumeration;

/**
 * Enumerates common size groups for various product categories.
 */
export interface SizeGroupEnumeration {
  [k: string]: unknown;
}
