/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Enumerates common size systems specific for wearable products
 */
export type WearableSizeSystemEnumeration = SizeSystemEnumeration;
/**
 * Enumerates common size systems for different categories of products, for example "EN-13402" or "UK" for wearables or "Imperial" for screws.
 */
export type SizeSystemEnumeration = SizeSystemEnumeration1 & SizeSystemEnumeration2;
export type SizeSystemEnumeration1 = "SizeSystemImperial" | "SizeSystemMetric";
export type SizeSystemEnumeration2 = string;
